//! Build script for edgeshield-oui.
//!
//! Parses the vendored IEEE OUI list (`data/oui.txt`) at build time and
//! generates a `phf::Map<u32, &str>` for O(1) vendor lookup at runtime.
//!
//! The OUI file is committed to the repo so builds are reproducible and
//! fully offline. To update the table, re-download the file:
//!
//! ```sh
//! curl -sSf -o crates/oui/data/oui.txt \
//!   https://standards-oui.ieee.org/oui/oui.txt
//! ```
//!
//! # Parsing
//!
//! The IEEE format has two lines per entry:
//!
//! ```text
//! 28-6F-B9   (hex)                Nokia Shanghai Bell Co., Ltd.
//! 286FB9     (base 16)            Nokia Shanghai Bell Co., Ltd.
//! ```
//!
//! We parse the `(base 16)` line: the first token is the 6-hex-digit OUI,
//! and the rest of the line (after the fixed column offset) is the
//! organization name. We store the OUI as a `u32` (big-endian 24-bit) and
//! the name as a `&'static str` baked into the generated code.

use std::collections::BTreeMap;
use std::env;
use std::fs::File;
use std::io::{BufRead, BufReader, Write};
use std::path::Path;

fn main() {
    // Re-run if the OUI data changes.
    println!("cargo:rerun-if-changed=data/oui.txt");

    let input = Path::new("data/oui.txt");
    let output = Path::new(&env::var("OUT_DIR").unwrap()).join("oui_map.rs");

    let entries = parse_oui_file(input);
    generate_phf_map(&entries, &output);

    println!(
        "cargo:warning=edgeshield-oui: generated {} OUI vendor entries",
        entries.len()
    );
}

/// Parse the IEEE OUI file into a sorted map of OUI (u32) → vendor name.
///
/// We use a `BTreeMap` to get deterministic output ordering, which makes
/// the generated code diff cleanly across updates.
fn parse_oui_file(path: &Path) -> BTreeMap<u32, String> {
    let file = File::open(path).expect("failed to open data/oui.txt");
    let reader = BufReader::new(file);

    let mut entries = BTreeMap::new();

    for line in reader.lines() {
        let line = match line {
            Ok(l) => l,
            Err(_) => continue,
        };

        // We only care about the "(base 16)" lines — they carry the
        // 6-hex-digit OUI and the organization name in one line.
        if !line.contains("(base 16)") {
            continue;
        }

        // Format: "286FB9     (base 16)            Nokia Shanghai Bell Co., Ltd."
        // The OUI is the first 6 chars. The name starts at a fixed column
        // (after "(base 16)" and whitespace). We find it by splitting on
        // "(base 16)" and trimming.
        let oui_hex = match line.get(..6) {
            Some(s) => s.trim(),
            None => continue,
        };

        let name = match line.split("(base 16)").nth(1) {
            Some(s) => s.trim(),
            None => continue,
        };

        if name.is_empty() {
            continue;
        }

        // Parse the 6 hex digits into a u32.
        let oui = match u32::from_str_radix(oui_hex, 16) {
            Ok(n) => n,
            Err(_) => continue,
        };

        // Escape the name for inclusion in a Rust string literal.
        entries.insert(oui, name.to_string());
    }

    entries
}

/// Generate a `phf::Map<u32, &str>` Rust source file.
///
/// We use `phf_codegen` to build a perfect hash function at compile time.
/// At runtime, `lookup` is a single hash + comparison — O(1), no
/// allocation, no I/O.
fn generate_phf_map(entries: &BTreeMap<u32, String>, output: &Path) {
    let mut map = phf_codegen::Map::<u32>::new();

    for (&oui, name) in entries {
        // Escape the name for a Rust string literal. phf_codegen handles
        // the key; we must escape the value ourselves.
        let escaped = escape_rust_str(name);
        map.entry(oui, &escaped);
    }

    let mut file = File::create(output).expect("failed to create oui_map.rs");

    // Emit the map as a static. The `phf` crate's `Map` is `Sync` and
    // `'static`, so it can be a top-level static. `DisplayMap` implements
    // `Display`, so we use `write!` to render it into the file.
    let built = map.build();
    writeln!(file, "// Auto-generated by build.rs. Do not edit.").unwrap();
    writeln!(
        file,
        "// Source: https://standards-oui.ieee.org/oui/oui.txt"
    )
    .unwrap();
    writeln!(file, "// {} entries", entries.len()).unwrap();
    writeln!(file).unwrap();
    write!(file, "pub static OUI_MAP: phf::Map<u32, &str> = ").unwrap();
    write!(file, "{built}").unwrap();
    writeln!(file, ";").unwrap();
}

/// Escape a string for inclusion in a Rust string literal.
///
/// Handles backslashes, double quotes, and newlines. phf_codegen expects
/// the value to be a valid Rust expression — a string literal is the
/// simplest choice.
///
/// Also strips invisible Unicode characters (zero-width spaces, etc.)
/// that appear in some IEEE OUI entries. Clippy's `invisible_characters`
/// lint denies these, and they serve no purpose in vendor names.
fn escape_rust_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        // Skip invisible characters that the IEEE data occasionally
        // contains (zero-width spaces, soft hyphens, etc.). These would
        // trip clippy's `invisible_characters` lint and add no value.
        if c.is_control() || unicode_width::UnicodeWidthChar::width(c) == Some(0) {
            continue;
        }
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}
