//! MAC OUI (Organizationally Unique Identifier) vendor lookup.
//!
//! Maps the first 3 bytes of a MAC address to the manufacturer name
//! registered with the IEEE. This is the primary signal for device
//! fingerprinting — it turns `B8:27:EB:...` into "Raspberry Pi
//! Foundation" so new-device alerts are actionable instead of opaque.
//!
//! # Offline-first
//!
//! The full IEEE OUI list (~39,000 entries) is vendored in
//! `data/oui.txt` and compiled into a perfect-hash map at build time.
//! There is no runtime download, no network dependency, no file to
//! ship alongside the binary. This preserves EdgeShield's "fully
//! offline" guarantee.
//!
//! # Lookup cost
//!
//! `lookup()` is a single perfect-hash lookup: O(1), no allocation,
//! no I/O. Safe to call on the packet hot path.
//!
//! # Updating the OUI table
//!
//! The IEEE publishes updates regularly. To refresh the table:
//!
//! ```sh
//! curl -sSf -o crates/oui/data/oui.txt \
//!   https://standards-oui.ieee.org/oui/oui.txt
//! ```
//!
//! The build script (`build.rs`) parses the file and regenerates the
//! map on every build that touches `data/oui.txt`.
//!
//! # Sources
//!
//! OUI assignments are public data published by the IEEE:
//! <https://standards-oui.ieee.org/oui/oui.txt>

// The perfect-hash map generated by build.rs. This file lives in
// OUT_DIR and is included here. It defines `pub static OUI_MAP`.
include!(concat!(env!("OUT_DIR"), "/oui_map.rs"));

use mac_address::MacAddress;

/// Look up the vendor name for a MAC address's OUI (first 3 bytes).
///
/// Returns a `&'static str` because the data is compiled in — no
/// allocation per lookup. Returns `None` for unregistered OUIs.
///
/// # Example
///
/// ```
/// use mac_address::MacAddress;
/// use std::str::FromStr;
/// use edgeshield_oui::lookup;
///
/// let mac = MacAddress::from_str("B8:27:EB:00:00:00").unwrap();
/// assert_eq!(lookup(&mac), Some("Raspberry Pi Foundation"));
/// ```
#[must_use]
pub fn lookup(mac: &MacAddress) -> Option<&'static str> {
    let [a, b, c, _, _, _] = mac.bytes();
    let oui = u32::from_be_bytes([0, a, b, c]);
    OUI_MAP.get(&oui).copied()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    #[test]
    fn test_raspberry_pi_lookup() {
        let mac = MacAddress::from_str("B8:27:EB:00:00:00").unwrap();
        assert_eq!(lookup(&mac), Some("Raspberry Pi Foundation"));
    }

    #[test]
    fn test_apple_lookup() {
        // 00:03:93 is a real Apple OUI.
        let mac = MacAddress::from_str("00:03:93:00:00:00").unwrap();
        assert_eq!(lookup(&mac), Some("Apple, Inc."));
    }

    #[test]
    fn test_unknown_oui_returns_none() {
        // 02:00:00 is the "locally administered" bit set — never assigned
        // by the IEEE, so it's guaranteed not to be in the OUI table.
        let mac = MacAddress::from_str("02:00:00:00:00:00").unwrap();
        assert_eq!(lookup(&mac), None);
    }

    #[test]
    fn test_lookup_uses_first_three_bytes_only() {
        // Same OUI, different last 3 bytes — should return same vendor.
        let mac1 = MacAddress::from_str("B8:27:EB:11:22:33").unwrap();
        let mac2 = MacAddress::from_str("B8:27:EB:AA:BB:CC").unwrap();
        assert_eq!(lookup(&mac1), lookup(&mac2));
        assert_eq!(lookup(&mac1), Some("Raspberry Pi Foundation"));
    }

    #[test]
    fn test_map_is_populated() {
        // Sanity check that the build script actually generated entries.
        // The full IEEE list has ~39,000 entries.
        assert!(
            OUI_MAP.len() > 30_000,
            "OUI map has only {} entries — expected >30,000. \
             Did the build script parse data/oui.txt correctly?",
            OUI_MAP.len()
        );
    }
}
