//! Device discovery for EdgeShield.
//!
//! This module maintains the device inventory. It receives decoded
//! and classified packets, updates the device table, and generates
//! events for the API layer.
//!
//! # Design
//!
//! The `DiscoveryEngine` is the stateful core of the system. It holds
//! a reference to the `DeviceStore` and processes packets by:
//!
//! 1. Extracting source/destination MAC and IP from the decoded packet
//! 2. Looking up or creating device records in the store
//! 3. Updating counters, IPs, and protocols
//! 4. Emitting events for the API layer
//!
//! # Concurrency
//!
//! The `DiscoveryEngine` is `Send + Sync` and designed to be called
//! from a single tokio task (the pipeline worker). The underlying
//! `DeviceStore` handles concurrent access from the API server.

use mac_address::MacAddress;
use std::sync::Arc;
use tokio::sync::mpsc;
use tracing::{info, span, trace, warn, Level};

use edgeshield_common::{Device, Protocol};
use edgeshield_oui;
use edgeshield_packet::capture::PacketBuf;
use edgeshield_packet::decode::{self, DecodedPacket};
use edgeshield_protocol::classifier;
use edgeshield_protocol::dhcp;
use edgeshield_protocol::mdns;
use edgeshield_storage::store::DeviceStore;

/// An event generated by the discovery engine.
///
/// Events are sent over an mpsc channel to the API layer for
/// potential WebSocket push or logging.
#[derive(Debug, Clone)]
pub enum DiscoveryEvent {
    /// A new device was discovered.
    DeviceDiscovered(Device),
    /// An existing device was updated.
    DeviceUpdated(Device),
    /// A previously-seen device has been silent for longer than a
    /// rule's threshold. Emitted by the background scanner in the
    /// daemon, not by the per-packet discovery engine.
    DeviceOffline(Device),
}

/// The discovery engine — the stateful core of EdgeShield.
///
/// Processes decoded packets and maintains the device inventory.
pub struct DiscoveryEngine {
    /// The device store (in-memory, backed by DashMap).
    store: Arc<dyn DeviceStore>,
    /// Channel for discovery events.
    event_tx: mpsc::Sender<DiscoveryEvent>,
}

impl DiscoveryEngine {
    /// Create a new discovery engine.
    pub fn new(
        store: Arc<dyn DeviceStore>,
        event_tx: mpsc::Sender<DiscoveryEvent>,
    ) -> Self {
        Self { store, event_tx }
    }

    /// Emit a `DeviceOffline` event for a device that has been silent.
    ///
    /// Called by the background scanner in the daemon. Uses `try_send`
    /// so a full channel doesn't block the scanner — the event is
    /// dropped with a log instead.
    pub async fn emit_offline_event(&self, device: Device) {
        let mac = device.mac;
        if self
            .event_tx
            .try_send(DiscoveryEvent::DeviceOffline(device))
            .is_err()
        {
            warn!(mac = %mac, "offline event channel full; dropping");
        }
    }

    /// Process a captured packet through the full pipeline.
    ///
    /// This is the main entry point. It:
    /// 1. Decodes the raw packet
    /// 2. Classifies the protocol
    /// 3. Updates the device table
    /// 4. Emits an event
    pub async fn process_packet(&self, buf: PacketBuf) {
        let span = span!(Level::TRACE, "process-packet");
        let _guard = span.enter();

        // Step 1: Decode
        let decoded = match decode::decode_packet(&buf) {
            Ok(d) => d,
            Err(e) => {
                trace!(error = %e, "failed to decode packet");
                return;
            }
        };

        // Step 2: Classify
        let protocol = classifier::classify(&decoded);

        // Step 2b: Extract DHCP hostname and vendor class if applicable
        let (dhcp_hostname, dhcp_vendor_class) = if protocol == Protocol::Dhcp {
            dhcp::parse_dhcp(decoded.payload)
                .map(|info| (info.hostname, info.vendor_class))
                .unwrap_or((None, None))
        } else {
            (None, None)
        };

        // Step 2c: Extract mDNS hostname if applicable. mDNS packets
        // carry service announcements with hostnames in SRV records —
        // far richer than a bare MAC for device identification. We
        // only set the hostname when DHCP hasn't already (DHCP is
        // authoritative; mDNS is a fallback).
        let mdns_hostname = if protocol == Protocol::Mdns {
            mdns::parse_mdns(decoded.payload).and_then(|info| info.hostname)
        } else {
            None
        };

        // Step 3: Update device table
        if let Err(e) = self
            .update_devices(
                &decoded,
                &protocol,
                dhcp_hostname,
                dhcp_vendor_class,
                mdns_hostname,
            )
            .await
        {
            warn!(error = %e, "failed to update devices");
        }
    }

    /// Update the device table from a decoded packet.
    async fn update_devices(
        &self,
        packet: &DecodedPacket<'_>,
        protocol: &Protocol,
        dhcp_hostname: Option<String>,
        dhcp_vendor_class: Option<String>,
        mdns_hostname: Option<String>,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let src_mac = MacAddress::new(packet.ethernet.source);
        let dst_mac = MacAddress::new(packet.ethernet.destination);

        let packet_len = packet.raw.raw.len() as u64;

        // Update source device
        let mut is_new_src = false;
        {
            let mut device = match self.store.get(&src_mac)? {
                Some(d) => d,
                None => {
                    is_new_src = true;
                    let mut d = Device::new(src_mac);
                    // Populate the vendor from the MAC OUI on first sight.
                    // This is a cheap O(1) perfect-hash lookup — safe on the
                    // hot path. We only do it once per device (at creation),
                    // not on every packet.
                    if let Some(vendor) = edgeshield_oui::lookup(&src_mac) {
                        d.vendor = Some(vendor.to_string());
                    }
                    d
                }
            };

            device.record_sent(packet_len, protocol.clone());

            // Set hostname from DHCP if available
            if let Some(ref hostname) = dhcp_hostname && device.hostname.is_none() {
                device.hostname = Some(hostname.clone());
                info!(mac = %src_mac, hostname, "hostname discovered via DHCP");
            }

            // Fall back to mDNS hostname if DHCP didn't provide one.
            // mDNS names are often richer (e.g., "living-room-apple-tv.local")
            // but DHCP is authoritative when present.
            if let Some(ref hostname) = mdns_hostname && device.hostname.is_none() {
                device.hostname = Some(hostname.clone());
                info!(mac = %src_mac, hostname, "hostname discovered via mDNS");
            }

            // Store the DHCP vendor class identifier (option 60) if
            // present and not already set. This is the client's
            // self-reported vendor class — distinct from the OUI
            // vendor which comes from the MAC registry.
            if let Some(ref vc) = dhcp_vendor_class && device.dhcp_vendor_class.is_none() {
                device.dhcp_vendor_class = Some(vc.clone());
                info!(mac = %src_mac, vendor_class = %vc, "DHCP vendor class discovered");
            }

            if let Some(ref ip) = packet.ipv4 {
                device.add_ip(ip.source);
                device.add_ip(ip.destination);
            }

            self.store.upsert(device.clone())?;

            if is_new_src {
                info!(mac = %src_mac, protocol = %protocol, "new device discovered");
                let _ = self.event_tx.try_send(DiscoveryEvent::DeviceDiscovered(device));
            } else {
                let _ = self.event_tx.try_send(DiscoveryEvent::DeviceUpdated(device));
            }
        }

        // Update destination device (if different from source)
        if src_mac != dst_mac {
            let mut is_new_dst = false;
            let mut device = match self.store.get(&dst_mac)? {
                Some(d) => d,
                None => {
                    is_new_dst = true;
                    let mut d = Device::new(dst_mac);
                    // Populate vendor from OUI on first sight (same as src).
                    if let Some(vendor) = edgeshield_oui::lookup(&dst_mac) {
                        d.vendor = Some(vendor.to_string());
                    }
                    d
                }
            };

            device.record_received(packet_len, protocol.clone());

            if let Some(ref ip) = packet.ipv4 {
                device.add_ip(ip.destination);
                device.add_ip(ip.source);
            }

            self.store.upsert(device.clone())?;

            if is_new_dst {
                info!(mac = %dst_mac, protocol = %protocol, "new device discovered");
                let _ = self.event_tx.try_send(DiscoveryEvent::DeviceDiscovered(device));
            } else {
                let _ = self.event_tx.try_send(DiscoveryEvent::DeviceUpdated(device));
            }
        }

        Ok(())
    }

    /// Get a reference to the device store.
    #[must_use] pub fn store(&self) -> &Arc<dyn DeviceStore> {
        &self.store
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use edgeshield_storage::memory::MemoryStore;

    /// Build a minimal Ethernet + IPv4 + TCP packet.
    fn build_test_packet(src_mac: &[u8; 6], dst_mac: &[u8; 6]) -> PacketBuf {
        let mut buf = Vec::with_capacity(54);

        // Ethernet header
        buf.extend_from_slice(dst_mac);
        buf.extend_from_slice(src_mac);
        buf.extend_from_slice(&[0x08, 0x00]); // IPv4

        // IPv4 header
        buf.push(0x45);
        buf.push(0x00);
        buf.extend_from_slice(&[0x00, 0x34]);
        buf.extend_from_slice(&[0x00, 0x00]);
        buf.extend_from_slice(&[0x40, 0x00]);
        buf.push(0x40);
        buf.push(0x06); // TCP
        buf.extend_from_slice(&[0x00, 0x00]);
        buf.extend_from_slice(&[0xc0, 0xa8, 0x01, 0x01]); // 192.168.1.1
        buf.extend_from_slice(&[0xc0, 0xa8, 0x01, 0x02]); // 192.168.1.2

        // TCP header
        buf.extend_from_slice(&[0x1f, 0x90]); // src 8080
        buf.extend_from_slice(&[0x00, 0x50]); // dst 80
        buf.extend_from_slice(&[0x00, 0x00, 0x00, 0x00]);
        buf.extend_from_slice(&[0x00, 0x00, 0x00, 0x00]);
        buf.push(0x50);
        buf.push(0x00);
        buf.extend_from_slice(&[0xff, 0xff]);
        buf.extend_from_slice(&[0x00, 0x00]);
        buf.extend_from_slice(&[0x00, 0x00]);

        PacketBuf::new(buf, 14)
    }

    #[tokio::test]
    async fn test_discovery_new_device() {
        let store = Arc::new(MemoryStore::new()) as Arc<dyn DeviceStore>;
        let (event_tx, mut event_rx) = mpsc::channel::<DiscoveryEvent>(100);
        let engine = DiscoveryEngine::new(store.clone(), event_tx);

        let src_mac = [0x00, 0x11, 0x22, 0x33, 0x44, 0x55];
        let dst_mac = [0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb];
        let buf = build_test_packet(&src_mac, &dst_mac);

        engine.process_packet(buf).await;

        // Should have discovered both devices
        let src_mac_addr = MacAddress::new(src_mac);
        let dst_mac_addr = MacAddress::new(dst_mac);

        let src_device = store.get(&src_mac_addr).unwrap().unwrap();
        assert_eq!(src_device.packet_count, 1);
        assert_eq!(src_device.bytes_sent, 54);

        let dst_device = store.get(&dst_mac_addr).unwrap().unwrap();
        assert_eq!(dst_device.packet_count, 1);
        assert_eq!(dst_device.bytes_received, 54);

        // Should have received events
        let event1 = event_rx.try_recv().unwrap();
        assert!(matches!(event1, DiscoveryEvent::DeviceDiscovered(_)));

        let event2 = event_rx.try_recv().unwrap();
        assert!(matches!(event2, DiscoveryEvent::DeviceDiscovered(_)));
    }

    #[tokio::test]
    async fn test_discovery_existing_device() {
        let store = Arc::new(MemoryStore::new()) as Arc<dyn DeviceStore>;
        let (event_tx, mut event_rx) = mpsc::channel::<DiscoveryEvent>(100);
        let engine = DiscoveryEngine::new(store.clone(), event_tx);

        let src_mac = [0x00, 0x11, 0x22, 0x33, 0x44, 0x55];
        let dst_mac = [0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb];

        // Process first packet
        let buf1 = build_test_packet(&src_mac, &dst_mac);
        engine.process_packet(buf1).await;

        // Clear events
        let _ = event_rx.try_recv();
        let _ = event_rx.try_recv();

        // Process second packet
        let buf2 = build_test_packet(&src_mac, &dst_mac);
        engine.process_packet(buf2).await;

        // Device should have updated counters
        let src_mac_addr = MacAddress::new(src_mac);
        let device = store.get(&src_mac_addr).unwrap().unwrap();
        assert_eq!(device.packet_count, 2);
        assert_eq!(device.bytes_sent, 108);

        // Should have received update events
        let event = event_rx.try_recv().unwrap();
        assert!(matches!(event, DiscoveryEvent::DeviceUpdated(_)));
    }
}
